Project INDICES {
  database_type: 'MySQL'
  Note: '''
    # Proyecto INDICES
  '''
}

// Las opciones de genero para alumnos y usuarios
Enum generos {
  H [note: 'Hombre']
  M [note: 'Mujer']
  X [note: 'Otro']
}

Enum tipos_ingresos {
  EX [note: 'Examen']
  EQ [note: 'Equivalencia']
  TR [note: 'Traslado']
  CO [note: 'Convalidación']
}

Enum tipos_titulaciones {
  TE [note: 'Tesis']
  RE [note: 'Residencia']
  DU [note: 'Modelo Dual']
}

Table personal {
  curp varchar(18) [pk, not null]
  nombre varchar [not null]
  paterno varchar [not null]
  materno varchar
  fecha_nacimiento date [not null]
  genero generos [not null, default: 'X']
  habla_lengua_indigena bool [not null]
  Note: 'Contiene la información personal del alumno'
}

Table alumnos {
  id int [pk, increment]
  no_control varchar(10) [not null]
  semestre_inicio int [not null]
  personal_id varchar(18) [not null]
  plan_id int [not null]
  Note: 'Contiene la información asociada al número de control del alumno'
}

Table carreras {
  id int [pk, increment]
  clave varchar [not null, unique]
  nombre varchar [not null]
  Note: 'Información general de una carrera'
}

Table planes {
  id int [pk, increment]
  clave varchar [not null, unique]
  fecha_inicio date [not null]
  fecha_final date
  carrera_id int [not null]
  Note: 'Plan de estudios, solo puede existir un plan de estudios activo a la vez'
}

Table ingresos {
  id int [pk, increment]
  periodo varchar(5) [not null]
  tipo tipos_ingresos
  alumno_id int [not null]
}

Table egresos {
  id int [pk, increment]
  periodo varchar(5) [not null]
  alumno_id int [not null]
}

Table titulaciones {
  id int [pk, increment]
  periodo varchar(5) [not null]
  tipo tipos_titulaciones
  alumno_id int [not null]
}

Table liberacioningles {
  id int [pk, increment]
  periodo varchar(5) [not null]
  alumno_id int [not null]
}

Table discapacidades {
  id int [pk, increment]
  nombre varchar [not null]
  descripcion varchar
  Note: 'Información general de una discapacidad'
}

Table personal_discapacidades {
  personal_id varchar(18) [not null]
  discapacidad_id int [not null]
  Note: 'Relación N:M para asociar discapacidades con un alumno'
}

Ref: discapacidades.id < personal_discapacidades.discapacidad_id
Ref: personal.curp < personal_discapacidades.personal_id
Ref: personal.curp < alumnos.personal_id
Ref: carreras.id < planes.carrera_id
Ref: planes.id < alumnos.plan_id
Ref: alumnos.id < ingresos.alumno_id
Ref: alumnos.id < egresos.alumno_id
Ref: alumnos.id < titulaciones.alumno_id
Ref: alumnos.id < liberacioningles.alumno_id