# Generated by Django 4.2.3 on 2024-02-06 18:41

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, validators=[usuario.models.Usuario.validate_name])),
                ('paternal_surname', models.CharField(max_length=150, validators=[usuario.models.Usuario.validate_name])),
                ('maternal_surname', models.CharField(max_length=150, null=True, validators=[usuario.models.Usuario.validate_name])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('X', 'Otro')], default='X', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('view_tablas_poblacion', 'Puede consultar Tablas de Poblacion'), ('view_tablas_crecimiento', 'Puede consultar Tablas de Crecimiento'), ('view_indices_permanencia', 'Puede consultar Indices de Permanencia'), ('view_indices_egreso', 'Puede consultar Indices de Egreso'), ('view_indices_titulacion', 'Puede consultar Indices de Titulacion'), ('view_indices_desercion', 'Puede consultar Indices de Desercion'), ('view_reportes_nuevo_ingreso', 'Puede consultar Reportes de Nuevo Ingreso'), ('view_reportes_egresados', 'Puede consultar Reportes de Egresados'), ('view_reportes_titulados', 'Puede consultar Reportes de Titulados'), ('view_cedulas_cacei', 'Puede consultar Cedulas de CACEI'), ('view_cedulas_caceca', 'Puede consultar Cedulas de CACECA')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
