# Generated by Django 4.2.3 on 2023-07-21 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('view_tablas_poblacion', 'Puede consultar Tablas de Poblacion'), ('view_tablas_crecimiento', 'Puede consultar Tablas de Crecimiento'), ('view_indices_permanencia', 'Puede consultar Indices de Permanencia'), ('view_indices_egreso', 'Puede consultar Indices de Egreso'), ('view_indices_titulacion', 'Puede consultar Indices de Titulacion'), ('view_indices_desercion', 'Puede consultar Indices de Desercion'), ('view_reportes_nuevo_ingreso', 'Puede consultar Reportes de Nuevo Ingreso'), ('view_reportes_egresados', 'Puede consultar Reportes de Egresados'), ('view_reportes_titulados', 'Puede consultar Reportes de Titulados'), ('view_cedulas_cacei', 'Puede consultar Cedulas de CACEI'), ('view_cedulas_caceca', 'Puede consultar Cedulas de CACECA')]},
        ),
    ]
