# Generated by Django 4.2.3 on 2023-08-25 02:32

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='second_last_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='maternal_surname',
            field=models.CharField(max_length=150, null=True, validators=[usuario.models.Usuario.validate_name]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='paternal_surname',
            field=models.CharField(default='Default', max_length=150, validators=[usuario.models.Usuario.validate_name]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=150, validators=[usuario.models.Usuario.validate_name]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
